source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'TXServerAddressManagerSwift_Example' do
  pod 'TXServerAddressManagerSwift', :path => '../'

  target 'TXServerAddressManagerSwift_Tests' do
    inherit! :search_paths

    
  end
end
